# Generated by Django 3.0.9 on 2020-09-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('profession', models.CharField(max_length=20)),
                ('myinterests', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('aboutme', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('postdata', models.DateField(auto_now_add=True)),
                ('label', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
